# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tex_gui.ui'
#
# Created: Wed Jul  7 22:33:36 2010
#      by: PyQt4 UI code generator 4.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(606, 710)
        self.buttonQuit = QtGui.QPushButton(Dialog)
        self.buttonQuit.setGeometry(QtCore.QRect(410, 670, 85, 28))
        self.buttonQuit.setObjectName("buttonQuit")
        self.buttonOK = QtGui.QPushButton(Dialog)
        self.buttonOK.setGeometry(QtCore.QRect(500, 670, 85, 28))
        self.buttonOK.setMaximumSize(QtCore.QSize(226, 16777215))
        self.buttonOK.setObjectName("buttonOK")
        self.layoutWidget = QtGui.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 570, 141, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.spinBox = QtGui.QSpinBox(self.layoutWidget)
        self.spinBox.setObjectName("spinBox")
        self.gridLayout_4.addWidget(self.spinBox, 0, 1, 1, 1)
        self.slidesSlider = QtGui.QSlider(self.layoutWidget)
        self.slidesSlider.setOrientation(QtCore.Qt.Horizontal)
        self.slidesSlider.setObjectName("slidesSlider")
        self.gridLayout_4.addWidget(self.slidesSlider, 2, 0, 1, 2)
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 370, 581, 191))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtGui.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEditAuthors = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditAuthors.setObjectName("lineEditAuthors")
        self.gridLayout.addWidget(self.lineEditAuthors, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEditTitle = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditTitle.setObjectName("lineEditTitle")
        self.gridLayout.addWidget(self.lineEditTitle, 1, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.layoutWidget1)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEditSubtitle = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditSubtitle.setObjectName("lineEditSubtitle")
        self.gridLayout.addWidget(self.lineEditSubtitle, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEditInstitute = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditInstitute.setObjectName("lineEditInstitute")
        self.gridLayout.addWidget(self.lineEditInstitute, 3, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.layoutWidget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.layoutWidget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.lineEditMail = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditMail.setObjectName("lineEditMail")
        self.gridLayout.addWidget(self.lineEditMail, 5, 1, 1, 1)
        self.lineEditDate = QtGui.QLineEdit(self.layoutWidget1)
        self.lineEditDate.setObjectName("lineEditDate")
        self.gridLayout.addWidget(self.lineEditDate, 4, 1, 1, 1)
        self.layoutWidget2 = QtGui.QWidget(Dialog)
        self.layoutWidget2.setGeometry(QtCore.QRect(12, 12, 581, 351))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtGui.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.textEntry = QtGui.QTextEdit(self.layoutWidget2)
        self.textEntry.setObjectName("textEntry")
        self.gridLayout_2.addWidget(self.textEntry, 0, 1, 1, 2)
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 1, 1, 1)
        self.buttonOpenFile = QtGui.QPushButton(self.layoutWidget2)
        self.buttonOpenFile.setObjectName("buttonOpenFile")
        self.gridLayout_2.addWidget(self.buttonOpenFile, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 2, 1, 1, 1)
        self.buttonOpenDir = QtGui.QPushButton(self.layoutWidget2)
        self.buttonOpenDir.setObjectName("buttonOpenDir")
        self.gridLayout_2.addWidget(self.buttonOpenDir, 2, 2, 1, 1)
        self.widget = QtGui.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(410, 570, 181, 81))
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtGui.QGridLayout(self.widget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.charsSpinBox = QtGui.QSpinBox(self.widget)
        self.charsSpinBox.setObjectName("charsSpinBox")
        self.gridLayout_5.addWidget(self.charsSpinBox, 0, 1, 1, 1)
        self.charsSlider = QtGui.QSlider(self.widget)
        self.charsSlider.setOrientation(QtCore.Qt.Horizontal)
        self.charsSlider.setObjectName("charsSlider")
        self.gridLayout_5.addWidget(self.charsSlider, 1, 0, 1, 2)
        self.label_12 = QtGui.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 0, 0, 1, 1)
        self.layoutWidget3 = QtGui.QWidget(Dialog)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 570, 241, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.gridLayout_3.addWidget(self.doubleSpinBox, 0, 1, 1, 1)
        self.keyWordPrioritySlider = QtGui.QSlider(self.layoutWidget3)
        self.keyWordPrioritySlider.setOrientation(QtCore.Qt.Horizontal)
        self.keyWordPrioritySlider.setObjectName("keyWordPrioritySlider")
        self.gridLayout_3.addWidget(self.keyWordPrioritySlider, 2, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQuit.setToolTip(QtGui.QApplication.translate("Dialog", "quit program", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonQuit.setText(QtGui.QApplication.translate("Dialog", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOK.setToolTip(QtGui.QApplication.translate("Dialog", "create presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOK.setText(QtGui.QApplication.translate("Dialog", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.spinBox.setToolTip(QtGui.QApplication.translate("Dialog", "number of slides", None, QtGui.QApplication.UnicodeUTF8))
        self.slidesSlider.setToolTip(QtGui.QApplication.translate("Dialog", "set number of slides", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Slides", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Author(s)", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditAuthors.setToolTip(QtGui.QApplication.translate("Dialog", "author(s) of the presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditTitle.setToolTip(QtGui.QApplication.translate("Dialog", "title of the presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Dialog", "Subtitle", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditSubtitle.setToolTip(QtGui.QApplication.translate("Dialog", "subtitle of the presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Institute", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditInstitute.setToolTip(QtGui.QApplication.translate("Dialog", "your institute", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Date", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "E-Mail", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditMail.setToolTip(QtGui.QApplication.translate("Dialog", "your mail address", None, QtGui.QApplication.UnicodeUTF8))
        self.lineEditDate.setToolTip(QtGui.QApplication.translate("Dialog", "date of presentation", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Text goes here", None, QtGui.QApplication.UnicodeUTF8))
        self.textEntry.setHtml(QtGui.QApplication.translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-style:italic; color:#aaaa7f;\">Text to be summarized</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "or select a file:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOpenFile.setToolTip(QtGui.QApplication.translate("Dialog", "open file dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOpenFile.setText(QtGui.QApplication.translate("Dialog", "Open File", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Dialog", "or select a directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOpenDir.setToolTip(QtGui.QApplication.translate("Dialog", "open a directory", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonOpenDir.setText(QtGui.QApplication.translate("Dialog", "Choose Dir", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Dialog", "Chars per Slide", None, QtGui.QApplication.UnicodeUTF8))
        self.doubleSpinBox.setToolTip(QtGui.QApplication.translate("Dialog", "keyword priority", None, QtGui.QApplication.UnicodeUTF8))
        self.keyWordPrioritySlider.setToolTip(QtGui.QApplication.translate("Dialog", "set keyword priority", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Keyword Priority", None, QtGui.QApplication.UnicodeUTF8))

